---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

Throughout my time in STAT 331 so far, I have seen improvement in my data visualization and data cleaning skills. Entering this class as a Quantitative Analysis concentration Business student, I had previous experience in both of these areas, but I grew in ways that I did not know I needed! I enjoy using data to solve ambiguous problems and have a larger impact. But, based on my feedback that I have received in this course so far, I’ve realized that at times, this has led me to not being fully intentional with the formatting and execution of my visualizations, or forgetting little details in cleaning data. These changes have made all the difference in how I approach data science concepts. 

With data visualization specifically, I grew in my knowledge of ggplot2. I have taken R classes previously, but always struggled with making my graphs look how I want, or even fully understanding how to plot different types of graphs. Using ggplot, I now understand how you can add different layers, add geoms, and add aesthetics to certain layers according to what you want your graph to look like. This has been extremely useful to know because now that I have this skill in R, I can translate this concept into other platforms. For example, I now know that having a line of best fit makes your scatterplot much easier to read and interpret, but I know how to make the line a different color in order for it to stand out to the viewer. Additionally, I know how to only apply transparency to the scatterplot in order for the viewer to see how the data points are distributed, rather than having solid points overlapping one another. Additionally, I appreciate Dr. Theobold being specific in their feedback for us to be thorough when it comes to axis labels and graph titles. Originally in Lab 2 Question 16, I did not include a labs() function to make my axis labels more specifically. Rather, I had just included the variable names as the axis labels. After receiving feedback, I now am more cognizant to include metrics in my axis labels, be specific about what kind of species this graph is referring to, and also to format my axis labels in a way where the reader won’t have to turn their head or put extra effort into reading it. As I mentioned earlier, I enjoy making graphs and pulling results from it. But I learned that it’s just as important for a reader who has no knowledge of the dataset, to be able to look at my graph and also see my findings. Without thorough labels, a comprehensive graph title, and unaesthetic axis, this purpose is not fulfilled. I’m glad to be improving in this area and hope to continue improving!

My data cleaning skills have significantly grown since being in this class, and most of it is related to the fact that I’ve learned so many new tools, specifically dyplr! Before this class, most of my data cleaning skills have taken place in excel, because my previous R classes would typically give us clean datasets and were more statistics focused. Learning how to filter, mutate, and join tables in R has been a game changer, as well as knowing how to do so efficiently in one pipeline. I have previous experience in SQL, which helped in my understanding of dyplr functions. But through this class, I have gained more experience in cleaning data in a hands on way where rather than being told specifically what steps to take, I’m given a scenario or problem to solve, and have to pull the correct data to answer it. A problem where I feel that this new skills is displayed is in Lab 5, where I am finding the initial suspect of the murder. Previous to this class, my thought process would be to hard code between tables, tracking the consistent person id’s until I found the suspect using the appropriate filters. I’m proud of my work in this lab, because I demonstrate my new knowledge of combining all these steps into one clean, tidy pipeline where I join tables to gather the data I need, rather than tracking id’s across different tables. Then, I filtered in that same pipeline! In an applied data science scenario, this is highly useful because in the case where we find additional clues and need to change filters, or need to find their income rather than their license plate number, it’s much easier to make these changes in this single pipeline! 

I’m proud to be growing in these areas, as they are relevant to data analyst roles that I hope to enter in the future. Having this foundation in R easily translates across several other tools and programs, and I will continue this class being sure to be intentional and concise in my data visualizations, and efficient in my data cleaning.
