---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If \[Name of Student\] doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning.

    Eva Moylan. They are extremely intentional to learn, rather than just getting assignments done.

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    Taking what we learned in lecture and being able to apply it in a more advanced way through labs, which were typically a level up from what we reviewed in class.

3.  What was the easiest part of the class for you? Explain why.

    Learning what different dyplr functions do, as I have taken SQL classes before and there are lots of similarities!

4.  What part of the class surprised or interested you the most? Explain why.

    I was surprised at how much we are able to customize graphs in ggplot, because I've never thoroughly understood how to use it in the past.

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

    Take full advantage of being able to submit revisions, because it really does help with letting new skills and knowledge settle in your brain quicker!
